### PR TITLE
Ready for Google Fonts

### PR DESCRIPTION
**Pull request by yanone**
Hi,

I've mastered the fonts ready to be published in Google Fonts.
As we're working with Glyphs sources, those are the ones I have used.

Please mere my Pull Request before we can proceed with the publishing.
Thank you!

### CODE REVIEW

**Comment by RosaWagner** [comment]
Hello,
This initiative looks unusual. May I ask who do you represent ?
In any case, you are welcome to contact the ANRT through [this form](https://anrt-nancy.fr/en/presentation-en/#contact) to submit any legitimate demand.
Thank you

**Comment by yanone** [comment]
I work as an external supplier for Google Fonts and was commissioned by Google Fonts to prepare Baskervville to comply to Google Fonts technical specifications, so it can be added to the Google Fonts library reachable under http://fonts.google.com.

As you published it under OFL license, any library is free to add it to their repertoire and distribute it.

Your own remark
> Feel free to pull requests and suggest improvement !

supports my request.

This is as far as my understanding goes.
As to how Baskervville was added to Google Fonts’ wish list and who put it there – I can’t answer. Maybe @davelab6 or @m4rc1e (both Google Fonts) can help? But the basic guess is that someone suggested it as a high quality and very interesting addition to the repertoire, and I agree.

**Comment by yanone** [comment]
You have already been contacted by @m4rc1e with a quality report of Baskervville in August, and have replied to that, so I was under the impression that you know of Google Fonts’ interests. 
My apologies if this comes as a surprise to you.

**Comment by RosaWagner** [comment]
Ok, it is a surprise. So indeed, someone sent a report and I thought it was genuine kindness from the open source community since no one has been clear regarding their interests. Honestly, I am not working on this project anymore, I definitely can't take a decision…people can definitely use and improve the font if they want, but Google Font is not any library. Whatever the license says, please contact ANRT's director (Thomas Huot-Marchand) through this form to discuss it, it will be highly appreciated: https://anrt-nancy.fr/en/presentation-en/#contact 

Thank you

**Comment by yanone** [comment]
Hi Rosalie,

I received the OK from Thomas Huot-Marchand to go ahead with the publishing, as long as the story of the typeface as well as the ANRT credits are published, which of course they were going to anyway.

If you could please merge the PR?
Thank you :)

**Pull request merged**
